config/routes.rb
Wiki::Application.routes.draw do
  
  get "users/edit"

  devise_for :users
  resources :categories
  resources :articles do
    resources :notifications do
      get 'deliver', :on => :collection
    end
  end

  resources :home
  resources :users
  
  match '/profile' => "users#show", :as => :profile
  
  root :to => "home#index"
  

  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  acts_as_taggable
  has_friendly_id :name, :use_slug => true, :approximate_ascii => true
  
  belongs_to :category
  belongs_to :user
  validates  :name, :user, :presence => true
  validates  :content, :description, :category, :presence => { :if => :published? }
  
  scope :published,     where({:published => true})
  scope :drafts,        where({:published => false}).order("updated_at DESC")
  scope :by_popularity,  order("hit_count DESC") # Not used right now

  def self.most_recent(qty)
    order("created_at DESC").limit(qty)
  end

  def increase_count!
    self.hit_count += 1
    self.save!
  end
  
  def self.search(query)
    if query.blank?
      published
    else
      conditions = []
      conditions << sanitize_sql(["articles.name #{$like} ?", "%#{query}%"])
      conditions << sanitize_sql(["articles.description #{$like} ?", "%#{query}%"])
      conditions << sanitize_sql(["articles.content #{$like} ?", "%#{query}%"])
      tags_conditions = sanitize_sql(["tags.name #{$like} ?", "%#{query}%"])
      conditions << "articles.id IN (SELECT taggings.taggable_id FROM taggings JOIN tags ON taggings.tag_id = tags.id AND (#{tags_conditions}) WHERE taggings.taggable_type = 'Article')"
      where(conditions.join(" OR ")).published
    end
  end

  def publish
    self.published = true
  end
  
  def publish!
    self.publish
    self.save!
  end
  
  def unpublish
    self.published = false
  end
  
  def published?
    self.published
  end
  
  def category_name
    self.category.name if self.category
  end
  
  def set_status!(publish=nil, draft=nil)
    if publish.blank?
      self.unpublish
    else
      self.publish
    end
  end
 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_filter :warn_if_article_published, :only => [:edit]

  def index
    @articles = Article.search(params[:q])
  end

  def show
    @article.increase_count!
    render :layout => "lightbox" if params[:lightbox]
  end

  def new
  end

  def edit
  end

  def create
    @article = current_user.articles.build(params[:article])
    @article.set_status!(params[:publish], params[:draft])
    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => I18n.t("notice.article.created_successfully")) }
        format.js {}
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  def update
    params[:article][:tag_list] ||= []
    @article.set_status!(params[:publish], params[:draft])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => I18n.t("notice.article.updated_successfully")) }
        format.js {}
      else
        format.html { render :action => "edit" }
        format.js
      end
    end
  end

  def destroy
    @article.destroy
    redirect_to(@article, :notice => I18n.t("notice.article.deleted_successfully"))
  end

  private

  def warn_if_article_published
    flash[:alert] = I18n.t("alert.article.warn_about_published_article_edit") if @article.published
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def tags_hidden_fields(article)
    list_elements = "".html_safe
    article.tag_list.each do |tag_name|
      list_elements += content_tag(:li, content_tag(:span, tag_name) + content_tag(:a, "X", :href => "#") +
      content_tag(:input, nil, :type => "hidden", :value => tag_name, :name => "article[tag_list][]"))
    end

    content_tag(:ul, list_elements, :id => "tag_list")
  end
  
  def render_textile_design_guide
    TEXTILE_GUIDE.display
  end
  
  def saved_timestamp(article)
    if article.new_record?
      text = "No se ha guardado"
    else
      text = "Guardado: " + content_tag(:span, time_ago_in_words(article.updated_at, true))
    end
    return text.html_safe
  end
  
  def link_to_preview(article, options={})
    options = {:id => "preview" , :class => "smallbutton"}
    if article.new_record?
      options[:style] = "display: none;"
      link_path = "#"
    else
      link_path = article_path(article, :lightbox => true)
    end
    
    link_to t(:preview), link_path, options
  end
  
  def can_suscribe?(article, user)
    article.new_record? || article.user == user
  end
end

app/views/articles/_article.html.erb
<div class="toparticle"><!--toparticle-->
  <a href="<%= article_path(article) %>">
    <h3><%= article.name %></h3>
    <%= article_admin_links(article) %>
    <p><%= redcloth(article.description) %></p>
  </a>
</div><!--/toparticle-->

app/views/articles/_disqus.html.erb
<% if APP_CONFIG[:disqus] %>
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    var disqus_shortname = "<%= APP_CONFIG[:disqus] %>";

      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>

  <noscript>
    Please enable JavaScript to view the 
    <a href="http://disqus.com/?ref_noscript">
      comentarios de blog traido por <span class="logo-disqus">Disqus</span>
    </a>
  </noscript>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:id => "article_form"}) do |f| %>
  <%= render "/layouts/error_messages", :target => @article %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4 %>
  </div>
  <div class="field">
    <%= f.label :content %>
	  <%= link_to t('.style_guide'), "#", :id => "toggle", :class => "smallbutton" %>
	  
	  <%= link_to_preview(@article) %>
	<br />
	<div id="togglebox" style="display: none;">
		<%= render_textile_design_guide %>
	</div>
	<br />
    <%= f.text_area :content, :rows => 30 %>
  </div>

  <div class="box">
    <div class="field">
      <%= f.label :category %>
      <%= f.select :category_id, Category.all.collect{|c| [c.name, c.id] }, :include_blank => true %>
    </div>

    <% if can_suscribe?(f.object, current_user) %>
      <div class="field">
        <%= f.check_box :author_suscribed %>
        <%= f.label :author_suscribed %>
      </div>
    <% end %>

    <div class="field">
      <%= label_tag :tag %>
      <%= text_field_tag :tag %>
      <%= link_to "Agregar Tag", "#", :id => "add_tag" %>
      <%= tags_hidden_fields(@article) %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit t('.save_draft'), :name => "draft" %>
    <%= f.submit t('.save_and_publish'), :name => "publish" %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  var tags = []
  <% ActsAsTaggableOn::Tag.all.each do |tag| %>
    tags.push('<%= tag.name %>')
  <% end %>
  
  $("input#tag").autocomplete({source: tags})
</script>

app/views/articles/create.js.erb
<% if @article.valid? %>
  var form = $("form#article_form");
  form.append("<input type='hidden' name='_method' value='put'/>");
  form.attr("action", "/articles/<%= @article.cached_slug %>");

  $("div#saved").html('Guardado: <span><%= time_ago_in_words(@article.updated_at, true)%></span>');
<% else %>
  <div id="name" class >
  </div>

  $("#errorExplanation").slideUp('slow', function(){ $(this).remove() })
  $("a#preview").show().attr("href", "<%= article_path(@article, :lightbox => true) %>")
  $("div#saved").html('<%= saved_timestamp(@article) %>');
<% end %>

app/views/articles/edit.html.erb
<div class="form_header">
  <h1 class="form"><%= t('.edit_article')%></h1>
  <div id="saved"><%= saved_timestamp(@article) %></div>
</div>

<div class="content">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h1><%= t('.listing_articles')%></h1>

<%= render @articles %>

app/views/articles/new.html.erb
<div class="form_header">
  <h1 class="form"><%= t('.new_article')%></h1>
  <div id="saved"><%= saved_timestamp(@article) %></div>
</div>

<div class="content">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="header">
  <h1 class="title"><%= @article.name %></h1>
  <span id="created_at">
    Creado el <%= l @article.created_at, :format => :summary %>
  </span>
  <div class="description">
    <%= redcloth(@article.description) %>
    <div class="tags">
      <ul>
        <% @article.tag_list.each do |tag| %>
          <li><%= tag %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="content">
  <%= redcloth(coderay(@article.content).html_safe) %>
</div>

<%= render :partial => 'articles/disqus' %>

<span style="display:none" id="article_id"><%= @article.id %></span>
<% unless params[:lightbox] %>
  <% if can? :modify, @article %>
    <div id="article_actions">
      <%= link_to t(:edit), edit_article_path(@article), :class => "button" %> |
      <%= link_to t(:destroy), article_path(@article), :method => :delete, :confirm => t(:sure), :class => "button" %>
    </div>
  <% end %>
<% end %>

app/views/articles/update.js.erb
$("#errorExplanation").slideUp('slow', function(){ $(this).remove() })

$("div#saved").html('<%= saved_timestamp(@article) %>');