config/routes.rb
Wiki::Application.routes.draw do
  
  get "users/edit"

  devise_for :users
  resources :categories
  resources :articles do
    resources :notifications do
      get 'deliver', :on => :collection
    end
  end

  resources :home
  resources :users
  
  match '/profile' => "users#show", :as => :profile
  
  root :to => "home#index"
  

  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many  :articles, :order => "name ASC"
  has_many  :published, :conditions => {:published => true}, :class_name => "Article"
  has_many  :drafts, :conditions => {:published => false}, :class_name => "Article"
  
  default_scope order("categories.name ASC")

  def self.with_published_articles
    includes(:articles).where("articles.published = ?", true)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @categories = Category.all

  end

  def show
    
  end

  def new
  end

  def edit
  end

  def create
    if @category.save
      redirect_to(@category, :notice => I18n.t("notice.category.created_successfully")) 
    else
      render :action => "new" 
    end
  end

  def update
    if @category.update_attributes(params[:category])
      redirect_to(@category, :notice => I18n.t("notice.category.updated_successfully")) 
    else
      render :action => "edit" 
    end
  end

  def destroy
    @category.destroy
    redirect_to(categories_url, :notice => I18n.t("notice.category.deleted_successfully"))
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { class: "small_form"}) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t(:name) %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit  t('.create_category')%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t(".edit_category") %></h1>

<%= render 'form' %>

<div class="action_links">
  <%= link_to t(".show_category"), @category %> |
  <%= link_to 'Cancelar', :back %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.categories')%></h1>

<table class="category">
  <tr>
    <th><%= t(:name)%></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>

    <% if user_signed_in? %>
      <td><%= link_to t(:edit), edit_category_path(category) %></td>
      <td><%= link_to t(:destroy), category, :confirm => '¿Estás seguro?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<div class="action_links">
  <%= link_to t('.new_category'), new_category_path, class: "button" %>
  <%= link_to t('.view_articles'), articles_path %>
</div>

app/views/categories/new.html.erb
<h1><%= t('.new_category')%></h1>

<%= render 'form' %>

<div class="action_links">
  <%= link_to t('.view_categories'), categories_path %>
</div>

app/views/categories/show.html.erb
<h1>Información de <%= @category.name %></h1>

<p>
  <b><%= t(:name)%></b>
  <%= @category.name %>
</p>


<%= link_to t(:edit), edit_category_path(@category) %> |
<%= link_to t('.view_categories'), categories_path %>