config/routes.rb
Wiki::Application.routes.draw do
  
  get "users/edit"

  devise_for :users
  resources :categories
  resources :articles do
    resources :notifications do
      get 'deliver', :on => :collection
    end
  end

  resources :home
  resources :users
  
  match '/profile' => "users#show", :as => :profile
  
  root :to => "home#index"
  

  
  

end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="errorExplanation" class="error_messages">
    <h2><%= t('errors.template.header', :count => target.errors.size, :model => t("activerecord.models.#{target.class.name.downcase}"), :this => t("activerecord.attributes.#{target.class.name.downcase}.this")) %></h2>
    <ul>
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-19105469-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_sidemenu.html.erb
<div id="search" style='position:relative'>
  <%= form_tag(articles_path, :method => 'get') do %>
    <%= text_field_tag :q, nil, placeholder: 'Buscar...' %>
    <%= submit_tag "", :class => "search", style: 'position:absolute; top:1px;right:2px;'  %>
  <% end %>
</div>

<div id="menu">
  <% published_categories.each do |category| %>
    <div class='filter'>
      <h1 class='filter-group'><%= category.name %></h1>

      <%# --- Be warned!! I used javascript to hide this categories.. --- %>

      <ul>
        <% get_and_sort_articles(category).each do |article| %>
          <li><%= active_tab article.name, article_path(article) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_uservoice.html.erb
<script type="text/javascript">
  var uvOptions = {};
(function() {
 var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
 uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/uJnfcFIRP9es9b4s7emQw.js';
 var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
 })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta name="google-site-verification" content="g23NnEJRw-USebKOPMhESQJcDmQhIsTXcnBKtkjJu0U" />
    <title>Wiki Innku</title>
    <%= stylesheet_link_tag 'application', 'jquery.ui.all', 'coderay', 'jquery.fancybox' %>
    <%= javascript_include_tag 'jquery', 'jquery-ui','application', 'rails', 'jquery.fancybox' %>
    <%= csrf_meta_tag %>
    <%= render "/layouts/google_analytics" %>
  </head>
  <body>
    <div id="doc3" class="yui-t3">
      <div id="hd"><!--hd-->
        <%= link_to image_tag("INNKU.png"), root_path %>
        
        <div id="login">
          <% if user_signed_in? %>
            <p><%= current_user.email %>, 
            <%= link_to t('.profile'), profile_path %> |
              <%= (link_to(t('.create_user'), new_user_path) + " |") if current_user.admin? %> 
              <%= (link_to(t('.new_article'), new_article_path) + " |")  %>
              <%= (link_to(t(:categories_link), categories_path) + " |") if can? :manage, Category %>
              <%= link_to t('.log_out'), destroy_user_session_path %></p>
          <% else %>
            <div><%= t('.guest')%> <%= link_to t('.sign_in'), new_user_session_path %></div>
          <% end %>
        </div>
      </div><!--/hd-->

      <div id="bd">
        <div id="yui-main"> 
          <div class="yui-b"><!--yui-b main column-->

            <% flash.each do |name, message| %>
              <div id="<%= name %>" class="flash"><%= message %></div>
            <% end %>

            <%= yield %>
          </div><!--/yui-b main column-->
        </div>

        <div id="yui-s" class="yui-b"><!--yui-b secondary column-->
          <%= render :partial => "/layouts/sidemenu"  %>
        </div><!--/yui-b secondary column-->

      </div>
      <div id="ft">
        <!-- PUT FOOTER CODE HERE -->
      </div>
    </div>
    <%= render "/layouts/uservoice" %>
  </body>
</html>

app/views/layouts/lightbox.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <title>Wiki Innku</title>
    <%= stylesheet_link_tag 'application', 'coderay' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>